global:
  scrape_interval:     15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'promtail'
    static_configs:
    - targets: ['promtail:9080']

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'reverse-proxy'
    static_configs:
    - targets: ['reverse-proxy:8080']

  - job_name: 'cardano-nodes'
    file_sd_configs:
    - files:
      - 'cardano.json'


