services:
  mithril-aggregator:
    environment:
      - DMQ_NODE_SOCKET_PATH=/ipc/dmq.socket

  mithril-aggregator-relay:
    volumes:
      - ../data/${NETWORK}/mithril-aggregator/cardano/ipc:/ipc
    environment:
      - DMQ_NODE_SOCKET_PATH=/ipc/dmq.socket
