[package]
name = "mithril-dmq"
description = "Mechanisms to publish and consume messages of a 'Decentralized Message Queue network' through a DMQ node"
version = "0.1.22"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
include = ["**/*.rs", "Cargo.toml", "README.md", ".gitignore"]

[package.metadata.cargo-machete]
# `serde_bytes` is used for DmqMessage serialization
ignored = ["serde_bytes"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { version = "=2.0.1" }
blake2 = "0.10.6"
hex = { workspace = true }
mithril-cardano-node-chain = { path = "../cardano-node/mithril-cardano-node-chain" }
mithril-common = { path = "../../mithril-common" }
pallas-codec = { version = "0.35.0" }
pallas-network = { version = "0.35.0" }
serde = { workspace = true }
serde_bytes = "0.11.19"
slog = { workspace = true }
slog-scope = "4.4.0"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt-multi-thread"] }

[dev-dependencies]
mockall = { workspace = true }
slog-async = { workspace = true }
slog-term = { workspace = true }
