version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./cardano-configurations/network/testnet:/config
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/config/cardano-node/config.json"
      , "--topology", "/config/cardano-node/topology.json"
      , "--database-path", "/db"
      ]

  mithril-aggregator:
    image: ghcr.io/input-output-hk/mithril-aggregator:${IMAGE_ID:-latest}
    restart: always
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    ports:
      - "80:8080"

  mithril-signer:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=testnet
      - PARTY_ID=0
      - RUN_INTERVAL=2
      - DB_DIRECTORY=/db
    volumes:
      - ./testnet/node.db:/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  promtail:
    image: grafana/promtail:1.4.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
