version: "3.9"

services:
  cardano-node:
    image: cardano-node/1.35.2-modified
    build:
      context: .
      dockerfile: Dockerfile.cardano
    user: ${CURRENT_UID}
    profiles:
      - cardano
      - all
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./cardano-configurations/network/testnet:/config
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket # used by cardano-cli
    command:
      [
        "run",
        "--config",
        "/config/cardano-node/config.json",
        "--topology",
        "/config/cardano-node/topology.json",
        "--database-path",
        "/db"
      ]

  mithril-aggregator-reverse-proxy:
    image: traefik:2.8
    restart: always
    user: "${CURRENT_UID}:${DOCKER_GID}"
    profiles:
      - reverse-proxy
      - all
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mithril-aggregator:
    image: ghcr.io/input-output-hk/mithril-aggregator:${IMAGE_ID:-latest}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - NETWORK_MAGIC=1097911063
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
      - NETWORK=${NETWORK:-testnet}
      - PROTOCOL_PARAMETERS__K=5
      - PROTOCOL_PARAMETERS__M=100
      - PROTOCOL_PARAMETERS__PHI_F=0.65
      - RUN_INTERVAL=60000
      - URL_SNAPSHOT_MANIFEST=https://storage.googleapis.com/cardano-${NETWORK:-testnet}/snapshots.json
      - SNAPSHOT_STORE_TYPE=local
      - SNAPSHOT_UPLOADER_TYPE=gcp
      - PENDING_CERTIFICATE_STORE_DIRECTORY=/mithril-aggregator/pending_cert_db
      - CERTIFICATE_STORE_DIRECTORY=/mithril-aggregator/cert_db
      - VERIFICATION_KEY_STORE_DIRECTORY=/mithril-aggregator/verification_key_db
      - STAKE_STORE_DIRECTORY=/mithril-aggregator/stake_db
      - SNAPSHOT_STORE_DIRECTORY=/mithril-aggregator/snapshot_db
      - SINGLE_SIGNATURE_STORE_DIRECTORY=/mithril-aggregator/single_signature_db
      - PROTOCOL_PARAMETERS_STORE_DIRECTORY=/mithril-aggregator/protocol_parameters_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./testnet/mithril-aggregator:/mithril-aggregator
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    ports:
      - "8080:8080"
    command:
      [
        "--db-directory",
        "/db",
        "--snapshot-directory",
        "/mithril-aggregator/snapshots",
        "--server-port",
        "8080",
        "-vvv"
      ]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.my-app.rule=Host(`aggregator.api.mithril.network`)'
      - 'traefik.http.routers.my-app.tls=true'
      - 'traefik.http.routers.my-app.tls.certresolver=lets-encrypt'

  mithril-signer-0:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=testnet
      - NETWORK_MAGIC=1097911063
      - PARTY_ID=pool1frevxe70aqw2ce58c0muyesnahl88nfjjsp25h85jwakzgd2g2l # IOG1 / https://testnet.cardanoscan.io/pool/48f2c367cfe81cac6687c3f7c26613edfe73cd329402aa5cf493bb61
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - STAKE_STORE_DIRECTORY=/mithril-signer-0/stake_db
      - PROTOCOL_INITIALIZER_STORE_DIRECTORY=/mithril-signer-0/protocol_initializer_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./testnet/mithril-signer-0:/mithril-signer-0
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  mithril-signer-1:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=testnet
      - NETWORK_MAGIC=1097911063
      - PARTY_ID=pool1987uhrx7pt5rea26sqsdrlenfclm2wxafd4rpspvz3qyqshnuyy # IOG2 / https://testnet.cardanoscan.io/pool/29fdcb8cde0ae83cf55a8020d1ff334e3fb538dd4b6a30c02c144040
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - STAKE_STORE_DIRECTORY=/mithril-signer-1/stake_db
      - PROTOCOL_INITIALIZER_STORE_DIRECTORY=/mithril-signer-1/protocol_initializer_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./testnet/mithril-signer-1:/mithril-signer-1
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  mithril-signer-2:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=testnet
      - NETWORK_MAGIC=1097911063
      - PARTY_ID=pool12luf5ysaxajd0g8dvtpuyxdchln363dhed8637psyx2eqzatmcv # Random unnamed pool / https://testnet.cardanoscan.io/pool/57f89a121d3764d7a0ed62c3c219b8bfe71d45b7cb4fa8f830219590
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - STAKE_STORE_DIRECTORY=/mithril-signer-2/stake_db
      - PROTOCOL_INITIALIZER_STORE_DIRECTORY=/mithril-signer-2/protocol_initializer_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./testnet/mithril-signer-2:/mithril-signer-2
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  mithril-signer-3:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=testnet
      - NETWORK_MAGIC=1097911063
      - PARTY_ID=pool17vmenrzf2ylr92t390wwhk3jn0ursx00sy92cfa807s3whyknrc # PIPE / https://testnet.cardanoscan.io/pool/f337998c49513e32a9712bdcebda329bf83819ef810aac27a77fa117
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - STAKE_STORE_DIRECTORY=/mithril-signer-3/stake_db
      - PROTOCOL_INITIALIZER_STORE_DIRECTORY=/mithril-signer-3/protocol_initializer_db
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./testnet/mithril-signer-3:/mithril-signer-3
      - ./testnet/node.db:/db
      - ./ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles:
      - tools
      - all
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  promtail:
    image: grafana/promtail:1.4.1
    profiles:
      - tools
      - all
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
