version: "3.9"

services:
  cardano-node:
    image: cardano-node/1.35.3-modified
    build:
      context: .
      dockerfile: Dockerfile.cardano
    user: ${CURRENT_UID}
    profiles:
      - cardano
      - all
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - ./cardano-configurations/network/${NETWORK}:/config
      - ./${NETWORK}/node.db:/db
      - ./ipc:/ipc
    environment:
      - CARDANO_SOCKET_PATH=/ipc/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket # used by cardano-cli
    command:
      [
        "run",
        "--config",
        "/config/cardano-node/config.json",
        "--topology",
        "/config/cardano-node/topology.json",
        "--database-path",
        "/db"
      ]

  mithril-aggregator-reverse-proxy:
    image: traefik:2.8
    restart: always
    user: "${CURRENT_UID}:${DOCKER_GID}"
    profiles:
      - reverse-proxy
      - all
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mithril-aggregator:
    image: ghcr.io/input-output-hk/mithril-aggregator:${IMAGE_ID:-latest}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
      - NETWORK=${NETWORK}
      - PROTOCOL_PARAMETERS__K=5
      - PROTOCOL_PARAMETERS__M=100
      - PROTOCOL_PARAMETERS__PHI_F=0.65
      - RUN_INTERVAL=60000
      - URL_SNAPSHOT_MANIFEST=https://storage.googleapis.com/cardano-${NETWORK}/snapshots.json
      - SNAPSHOT_STORE_TYPE=local
      - SNAPSHOT_UPLOADER_TYPE=gcp
      - DATA_STORES_DIRECTORY=/mithril-aggregator
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./${NETWORK}/mithril-aggregator:/mithril-aggregator
      - ./${NETWORK}/node.db:/db
      - ./ipc:/ipc
    ports:
      - "8080:8080"
    command:
      [
        "--db-directory",
        "/db",
        "--snapshot-directory",
        "/mithril-aggregator/snapshots",
        "--server-port",
        "8080",
        "-vvv"
      ]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.my-app.rule=Host(`aggregator.api.mithril.network`)'
      - 'traefik.http.routers.my-app.tls=true'
      - 'traefik.http.routers.my-app.tls.certresolver=lets-encrypt'

  mithril-signer-0:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=${NETWORK}
      - PARTY_ID=pool10g0tvpyc3phkym8r6hamdulyzd6shzjldpahyvdkljl7ur2adfe # ADA Capital / https://preview.cexplorer.io/pool/pool10g0tvpyc3phkym8r6hamdulyzd6shzjldpahyvdkljl7ur2adfe
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - DATA_STORES_DIRECTORY=/mithril-signer-0
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./${NETWORK}/mithril-signer-0:/mithril-signer-0
      - ./${NETWORK}/node.db:/db
      - ./ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  mithril-signer-1:
    image: ghcr.io/input-output-hk/mithril-signer:${IMAGE_ID:-latest}
    restart: always
    user: ${CURRENT_UID}
    profiles:
      - mithril
      - all
    environment:
      - RUST_BACKTRACE=1
      - AGGREGATOR_ENDPOINT=http://mithril-aggregator:8080/aggregator
      - NETWORK=${NETWORK}
      - PARTY_ID=pool1t2zfh44yjhgxxrmt563k0wjw9v7vc7jn29vpyyz4vrq4yk8k4m6 # APEX / https://preview.cexplorer.io/pool/pool1t2zfh44yjhgxxrmt563k0wjw9v7vc7jn29vpyyz4vrq4yk8k4m6
      - RUN_INTERVAL=60000
      - DB_DIRECTORY=/db
      - DATA_STORES_DIRECTORY=/mithril-signer-1
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI_PATH=/app/bin/cardano-cli
    volumes:
      - ./${NETWORK}/mithril-signer-1:/mithril-signer-1
      - ./${NETWORK}/node.db:/db
      - ./ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles:
      - tools
      - all
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  promtail:
    image: grafana/promtail:1.4.1
    profiles:
      - tools
      - all
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
