[package]
name    = "mithril-stm"
version = "0.2.9"
edition = { workspace = true }
authors = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A Rust implementation of Mithril Stake-based Threshold Multisignatures (STMs)."
categories = ["cryptography"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    ".gitignore",
]

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
blake2      = "0.10.4"
blst = { version = "0.3.10" }
digest      = { version = "0.10.5", features = ["alloc"] }
num-bigint  = { version = "0.4.0", optional = true }
num-rational = { version = "0.4.0", optional = true }
num-traits  = { version = "0.2.14", optional = true }
rand_core   = "0.6.3"
rayon       = "1.5.1"
rug = { version = "1.14", optional = true }
serde = { version = "1", features = ["rc", "derive"] }
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
criterion   = { version = "0.4.0", features = ["html_reports"] }
hex = "0.4.3"
num-bigint  = "0.4.0"
num-rational = "0.4.0"
proptest    = "1.0.0"
rand = "0.8"
rand_chacha = "0.3.1"

[[bench]]
name = "multi_sig"
harness = false
required-features = ["benchmark-internals"]

[[bench]]
name = "stm"
harness = false

[[bench]]
name = "size_benches"
harness = false

[features]
default = ["rug-backend"]
rug-backend = ["rug/default"]
num-integer-backend = ["num-bigint", "num-rational", "num-traits"]
portable = ["blst/portable"] # portable feature avoids SIGILL crashes on CPUs not supporting Intel ADX instruction set when built on CPUs that support it
benchmark-internals = [] # For benchmarking multi_sig
