[package]
name = "mithril-stm"
version = "0.3.30"
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A Rust implementation of Mithril Stake-based Threshold Multisignatures (STMs)."
categories = ["cryptography"]
include = ["**/*.rs", "Cargo.toml", "README.md", ".gitignore"]

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
blake2 = "0.10.6"
# Enforce blst portable feature for runtime detection of Intel ADX instruction set.
blst = { version = "0.3.13", features = ["portable"] }
digest = { version = "0.10.7", features = ["alloc"] }
rand_core = "0.6.4"
rayon = "1.10.0"
serde = { version = "1.0.214", features = ["rc", "derive"] }
thiserror = "1.0.67"

[target.'cfg(not(any(target_family = "wasm", windows)))'.dependencies]
# only unix supports the rug backend
rug = { version = "1.26.1", optional = true }
num-bigint = { version = "0.4.6", optional = true }
num-rational = { version = "0.4.2", optional = true }
num-traits = { version = "0.2.19", optional = true }

[target.'cfg(any(target_family = "wasm", windows))'.dependencies]
# WASM and Windows don't support rug backend, fallback to num-integer only
num-bigint = { version = "0.4.6" }
num-rational = { version = "0.4.2" }
num-traits = { version = "0.2.19" }

[dev-dependencies]
bincode = "1.3.3"
criterion = { version = "0.5.1", features = ["html_reports"] }
hex = "0.4.3"
num-bigint = "0.4.6"
num-rational = "0.4.2"
proptest = "1.5.0"
rand = "0.8.5"
rand_chacha = "0.3.1"

[[bench]]
name = "multi_sig"
harness = false
required-features = ["benchmark-internals"]

[[bench]]
name = "stm"
harness = false

[[bench]]
name = "size_benches"
harness = false

[features]
default = ["rug-backend"]
rug-backend = ["rug/default"]
num-integer-backend = ["num-bigint", "num-rational", "num-traits"]
portable = [] # deprecated, will be removed soon
benchmark-internals = [] # For benchmarking multi_sig
batch-verify-aggregates = [
] # For batch verification of multi-signatures (set automatically by build script)
