[package]
name = "mithril-protocol-config"
version = "0.1.4"
description = "Configuraton parameters for Mithril network"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
include = ["**/*.rs", "Cargo.toml", "README.md", ".gitignore"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
mithril-aggregator-client = { path = "../mithril-aggregator-client" }
mithril-common = { path = "../../mithril-common" }
tokio = { workspace = true }

[dev-dependencies]
httpmock = "0.8.1"
serde_json = { workspace = true }
slog = { workspace = true }
slog-async = { workspace = true }
slog-term = { workspace = true }
