[package]
name = "mithril-signed-entity-lock"
version = "0.0.5"
description = "A non-blocking lock mechanism for signed entity type."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
mithril-common = { path = "../../../mithril-common" }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
