[package]
name = "mithril-doc-derive"
version = "0.1.17"
description = "An internal macro to support documentation generation."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full"] }

[features]
default = []
