[package]
name = "mithril-cardano-node-chain"
version = "0.1.4"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
hex = { workspace = true }
mithril-common = { path = "../../../mithril-common" }
nom = "8.0.0"
pallas-addresses = { version = "0.33.0" }
pallas-codec = { version = "0.33.0" }
pallas-network = { version = "0.33.0" }
pallas-primitives = { version = "0.33.0" }
pallas-traverse = { version = "0.33.0" }
rand_core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["process"] }

[dev-dependencies]
kes-summed-ed25519 = { version = "0.2.1", features = [
    "serde_enabled",
    "sk_clone_enabled",
] }
mithril-common = { path = "../../../mithril-common", features = ["test_tools"] }
mockall = { workspace = true }
pallas-crypto = "0.33.0"
slog-async = { workspace = true }
slog-term = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
