name: Manual crates publication

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: |
          SHA of the commit on which the mithril crates should be obtained.
        required: true
        type: string
      package:
        description: |
          Packages(s) to be published to crates.io registry.
        required: true
        type: choice
        options:
          - all
          - mithril-stm
          - mithril-common
          - mithril-client
          - mithril-build-script
          - mithril-cardano-node-internal-database
      dry_run:
        description: Dry run will not publish to crates.io registry.
        required: true
        type: boolean
        default: true

jobs:
  publish-crate:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - package: mithril-stm
            api_token_secret_name: CRATES_IO_API_TOKEN
          - package: mithril-build-script
            api_token_secret_name: CRATES_IO_API_TOKEN_MITHRIL_BUILD_SCRIPT
          - package: mithril-common
            api_token_secret_name: CRATES_IO_API_TOKEN_MITHRIL_COMMON
          - package: mithril-aggregator-client,
            api_token_secret_name: CRATES_IO_API_TOKEN_MITHRIL_AGGREGATOR_CLIENT
          - package: mithril-aggregator-discovery,
            api_token_secret_name: CRATES_IO_API_TOKEN_MITHRIL_AGGREGATOR_DISCOVERY
          - package: mithril-cardano-node-internal-database
            api_token_secret_name: CRATES_IO_API_TOKEN_MITHRIL_CARDANO_NODE_INTERNAL_DATABASE
          - package: mithril-client
            api_token_secret_name: CRATES_IO_API_TOKEN_MITHRIL_CLIENT

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        if: inputs.package == matrix.package || inputs.package == 'all'
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.commit_sha }}

      - name: Install stable toolchain
        if: inputs.package == matrix.package || inputs.package == 'all'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: ${{ inputs.dry_run && 'Test publish' || 'Publish' }} package to crates.io
        if: inputs.package == matrix.package || inputs.package == 'all'
        uses: ./.github/workflows/actions/publish-crate-package
        with:
          dry_run: ${{ inputs.dry_run }}
          package: ${{ matrix.package }}
          api_token: ${{ secrets[matrix.api_token_secret_name] }}
